# Generated by Django 4.1.1 on 2022-09-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=150, unique=True)),
                ('vinculo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ('nome_autor',),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=150, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='Categorias')),
            ],
            options={
                'ordering': ('nome_categoria',),
            },
        ),
        migrations.CreateModel(
            name='NivelEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=150, unique=True, verbose_name='Nivel de Ensino')),
            ],
            options={
                'verbose_name': 'Nível de Ensino',
                'verbose_name_plural': 'Níveis de Ensino',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subcategoria', models.CharField(max_length=150, unique=True, verbose_name='Nome da Subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=150, verbose_name='Nome do Item')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
                ('imagem_apoio', models.ImageField(upload_to='Items', verbose_name='Imagem de Apoio')),
                ('arquivo_grt', models.FileField(upload_to='Items')),
                ('data_upload', models.DateField(auto_now=True)),
                ('autores', models.ManyToManyField(to='repositorio.autor')),
                ('categorias', models.ManyToManyField(to='repositorio.categoria')),
                ('niveis_ensino', models.ManyToManyField(to='repositorio.nivelensino')),
                ('subcategorias', models.ManyToManyField(to='repositorio.subcategoria')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ('nome_item', 'data_upload'),
            },
        ),
    ]
